### ISSUE TITLE
Typo in tandem.d.ts - Incorrect Syntax for Optional Boolean Parameter

### ISSUE THREAD

**Issue by pko67** [autodesk-tandem/tandem-viewer-react-2legged#2]
There is a typo in the tandem.d.ts file located [here](https://github.com/autodesk-tandem/tandem-viewer-react-2legged/blob/master/client/src/types/tandem.d.ts).

In line 57, the optional history parameter is incorrectly declared as:

`history: boolean?;`

It should be:

`history?: boolean;`

This change will correct the syntax for the optional boolean parameter. Please update the code to reflect this fix.

**Comment by liskaj** [comment]
Should be fixed now - see commit 8905460. I also added few additional methods which might be useful for external developers.
